###
POST http://localhost/mypharma/public/api/login
Content-Type: application/json

{
    "email": "as@gmail.com",
    "password": "12345678"
}


###
POST http://localhost/mypharma/public/api/register
Content-Type: application/json

{
    "email": "yosef@gmail.com",
    "name": "Yosef",
    "password": "12345678",
    "role": 5,
    "profession": 2
}


###

GET http://localhost/mypharma/public/api/news?page=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL215cGhhcm1hXC9wdWJsaWNcL2FwaVwvbG9naW4iLCJpYXQiOjE1OTgxNTg2ODcsImV4cCI6MTU5ODE2MjI4NywibmJmIjoxNTk4MTU4Njg3LCJqdGkiOiJSdVhDV1ZlZkJsREdld2J5Iiwic3ViIjo2LCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIn0.KmbGiRiosXUDgVf-hB9bZlw8qn66nFQAtiZ1baCXsyU
###



GET http://localhost/mypharma/public/api/products
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL215cGhhcm1hXC9wdWJsaWNcL2FwaVwvbG9naW4iLCJpYXQiOjE1OTgxNjYzMTcsImV4cCI6MTU5ODE2OTkxNywibmJmIjoxNTk4MTY2MzE3LCJqdGkiOiJmR2hTQVl6N01RRXVDamlsIiwic3ViIjo2LCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIn0.7wjRqH5krgEqs3E0OKd6UedE5Zr1n0gFHpLqiQL9XV0
###



GET http://192.168.1.2/mypharma/public/storage/news/2020052113533279714.PNG